Bookstore: styling
shihabrafio/BookStore pull request #5
Opened 2023-06-15 19:42 UTC by shihabrafio

This PR includes,

-   The concept of state management.
-   Use store, actions and reducers in React.
-   Connect React and Redux.
-   Apply React best practices and language style guides in code.

2023-06-15 20:49 UTC, alexander16108 requested changes
Hi @shihabrafio , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/FbN4MpJnIwLQc/giphy.gif"/>

## Highlights
✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 20:49 UTC, alexander16108 commented on src/components/Addbook.jsx
> +      border: solid 1px #e1e1e1;
- as seen below there should be some padding between the cards and the navbar
- as seen below the background of your books are different from the original design please fix this 👍🏾 
- your  book should have padding around the body of the book as seen below
- please remove the border around the see progress button 
- please use the correct font for this project which is `Roboto, Helvetica, sans-serif

your design
![image](https://github.com/shihabrafio/BookStore/assets/60612329/66180b81-7bd9-437e-a663-09a71405bfb1)

required design
![image](https://github.com/shihabrafio/BookStore/assets/60612329/1e02dc5d-8bba-469d-b8c8-6bcde5e7eb5d)

2023-06-15 20:49 UTC, alexander16108 commented on src/components/Addbook.jsx
> +      border: solid 1px #e1e1e1;
- your nav links should be correctly aligned to the centre with the header and user icon as seen below 👍🏾 
- the colour of the header which should be blue Is different from the original design please fix this error 👍🏾 
- the user icon should have some significant padding to the right to proper resemble the original design 

required design 
![image](https://github.com/shihabrafio/BookStore/assets/60612329/2f8c43ee-ff1d-4d69-8168-1c5557a6c0b9)

your design 
![image](https://github.com/shihabrafio/BookStore/assets/60612329/41b9f7db-1aa8-48ce-9aea-8d961b2460c1)

2023-06-16 06:39 UTC, topeogunleye approved these changes
### Hi @shihabrafio, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Styled Bookstore using correct padding, font style, button style, and font weight. ✔️ 
 
## [Optional] suggestions:
* For future pull requests, please notice that your branch name `style`does not follow the convention of being named after a feature or action. For example, you could name your branch `added-style`. This makes it easier to track the changes and the purpose of each branch.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 06:40 UTC, merged